// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkkslcmifoyfasizmend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxra3NsY21pZm95ZmFzaXptZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDc2NTUsImV4cCI6MjA3MDY4MzY1NX0.SuRJ3KHzRKt9bBbHvN4d_hjBmuDit2kdjtVZwYghHF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});